### ISSUE TITLE
Slashes in URL need to be escaped when using date math expr in index names

### ISSUE THREAD

**Issue by gskema** [ruflin/Elastica#1228]
My index name is `<log-{now/d-1d}>`. This index works fine for `_bulk` writes,
because it is placed inside the request body and doesn't need to be escaped.

However, if we use this index name for `_search` or other operations where index is specified in the URL, it needs to be escaped: `<log-{now%2Fd-1d}>` .

I image that the escaping should happen somewhere around here:

https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Transport/Http.php#L61

date_math expressions in index names are supported since `2.0`.
Our ES version is `2.4.1` and the package version is `3.2.3`

**Comment by ruflin** [comment]
Thanks for the feature request. It is definitively something we should add support for. I'm curious what happens if we escape the hole query, means if it will have some side effects. Did you already play around with it?

For reference, here the reference to date math in index: https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html

**Comment by gskema** [comment]
Which query are you speaking of? As far as I can work out, we should only escape **some** symbols in the request URI fragments, eg. `localhost:9200/<log-{now%2Fd-1d}>/_search?preference=_shards:1,2`

**Comment by ruflin** [comment]
@gskema Correct, sorry I meant URI, or better path instead of query. What I wanted to check is if we could escape the complete path or if there could be some side affects to this. We should probably just try it out.

**Comment by gskema** [comment]
I tried sending a query with fully escaped path, e.g. `%2F%3Clog-%7Bnow%2Fd%7D%3E%2F_refresh`, doesn't work (tried through Elastica and Sense).

When path is `/%3Clog-%7Bnow%2Fd%7D%3E/_refresh` ES responds correctly (resolves the name).

They've added a character escape map to the documentation in 5.x : https://www.elastic.co/guide/en/elasticsearch/reference/5.x/date-math-index-names.html

**Comment by ruflin** [comment]
@gskema Do you plan to open a PR for this change?

**Comment by gskema** [comment]
@ruflin I was going to, but I'm having trouble setting up a docker box on Windows at home. My fix would be adding a specific function to `Util` class for escaping relevant part of an already formed request **path**: https://gist.github.com/gskema/2e2ce6584737a3b66351e6ec77e8ce20 (WIP) and then using it in `Http`, `HttpAdapter` and `Guzzle` transports.

Would you say that this fix would be up the library's code standards? I would also write some functional tests for this function.

I though RegEx replace may be a bit too much, maybe even more difficult than the algorithm above. I thought that doing a quick check for `<` or `>` would good quickly bail if there is no date math in the index name.

**Comment by ruflin** [comment]
Oh, docker and windows ... Code looks good to me. I like that we don't use regexp as regexp can be become complex and inefficient. 

Was no thinking yet about the users that already escape it for reason X. You are right that this could breaking. To make it less intrusive perhaps we should also consider the idea to only apply it to the queries / places where date math can be used instead of the full url. So escaping is explicit to these parts. The main downside is that it requires implementation in lots of different places I assume.

**Comment by gskema** [comment]
@ruflin I think date math can be used in any index name, since the expression always resolves to a single date (explicit string). Why I think we should put in the actual transports: because the user can create an explicit `Request($path...)` object and the only viable place to put it is before sending actually it (at least from what I've gathered). Also, don't forget bulk operation. The idea is to use unescaped path everywhere and let the use forget about the actual escaping troubles (leave it to the implementation). I also considered that there might be some futuristic transport driver that doesn't use URI :D

**Comment by ruflin** [comment]
SGTM. Lets try it out and see what effect it will have. Can you open a PR? That makes it easier to discuss the details.
