### ISSUE TITLE
What versions of library is maintained and support?

### ISSUE THREAD

**Issue by oleg-andreyev** [ruflin/Elastica#1505]
From README, it's unclear what versions are maintained and supported.
Against what lowest version PR could be submitted?

P.S.
Thanks to **all** contributors and @ruflin for their work and many hours spent for this library.

**Comment by ruflin** [comment]
Master is currently identical to 6.x so this is the most maintained version. But I recently published a version for the 5.x branch which especially the community still backport things. Does this answer your question?

**Comment by oleg-andreyev** [comment]
Q: So 2.x / 3.x (which are for ES 2.x) aren't maintained?

I think it would be great to reflect this information in README or CONTRIBUTING files, so that users would be aware that version of lib is maintained and PR could created against certain versions, what do you think?

**Comment by ruflin** [comment]
@oleg-andreyev Happy to accept a PR here. In general it can be said that it mostly follows EOL dates from Elasticsearch: https://www.elastic.co/support/eol Main difference is that new features or mostly added only to new release and the previous major is only touched when really needed.

For 2.x/3.x: There weren't any PR's in quite some time. Probably also because there is no 3.x branch :-)

**Comment by oleg-andreyev** [comment]
@ruflin I would be happy to create PR, will do it, but before just wanted to have clear understanding, thanks!

**Comment by ruflin** [comment]
@oleg-andreyev Thanks. Probably the part that we should specify is what "maintained" means.
