### ISSUE TITLE
Update a tag in the 2.x branch.

### ISSUE THREAD

**Issue by maximenko** [ruflin/Elastica#1520]
Hello. Can we update a tag version in the 2.x branch? Now newest version is the 2.3.1, but the 2.x branch is behind the 2.3.1 tag who resolve problem with php 7.2.

Thanks.

**Comment by ruflin** [comment]
There are currently two commits difference: https://github.com/ruflin/Elastica/compare/2.3.1...2.x

I'm actually a bit concerned about the first one not the PHP 7.2 one as I never really tested it and it could have some unwanted side effects. The reason of the 2.x branch was at the time it was created not to do release on it but have still a branch for people to do contributions if needed.

With the problem of PHP 7 popping up, it's not nice obviously.

The reason I'm very hesitant to do a release is because Elastica and Elasticsearch versions this is running against are highly likely already EOL. More importantly, I don't want to break anything for someone running the current 2.3.1. 

What Elasticsearch version are you running against? Could you run against the 2.x branch?

**Comment by maximenko** [comment]
I use the 1.6.2 version of the Elasticsearch. And in this time for me important upgrade the version for Elastica. In the near future I can't upgrade the Elasticsearch version.

**Comment by maximenko** [comment]
Sorry, but I can't do it. Because I use https://github.com/FriendsOfSymfony/FOSElasticaBundle/tree/3.2.x and it use ^2.1

I will be happy if you understand me! :)
Thanks.

**Comment by ruflin** [comment]
An alternativ we could do is creating a second 2.x branch, get the commit for PHP 7 in this branch and tag a release on top of it. Like this we would not have the risk of the other PR. Would you be interested to take on this work?

**Comment by maximenko** [comment]
What I should do?

**Comment by ruflin** [comment]
@maximenko Did not forget you here. We need to create a separate branch, cherry pick the commit and make a release based on it. I just realised writing this that I must do it because of access rights. Will try to get it done next week.

**Comment by ruflin** [comment]
@maximenko Better late then never? So there is now a tag `2.3.2`: Can you check if it is what you needed?

**Comment by jmsche** [comment]
@ruflin Thanks for tagging it :) Works great for me.
