### ISSUE TITLE
Not compatible with the php 5.3.3 version

### ISSUE THREAD

**Issue by bdlabs** [ruflin/Elastica#1559]
https://github.com/ruflin/Elastica/blob/51faf4fd6c3e80c121dc30776d8f3f6e56ea7a8f/lib/Elastica/Query.php#L404

This is not compatible with the php 5.3.3 version

if (isset($this->_params['post_filter']) && 0 === count(($this->_params['post_filter'])->toArray())) {
            unset($this->_params['post_filter']);
}

request.CRITICAL: Symfony\Component\Debug\Exception\FatalErrorException: Parse Error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) (uncaught exception)

**Comment by jmsche** [comment]
PR'd in #1561. Sorry for the miss, too much used to PHP 7+ :)

**Comment by killerwolf** [comment]
I'am facing the same issue 
I upgraded from 2.3.1 to 2.3.2 (because i am still using ES 1.7 with PHP5.6)

`Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Parse Error: syntax error, unexpected '->' (T_OBJECT_OPERATOR)" at /var/www/application/vendor/ruflin/elastica/lib/Elastica/Query.php line 404`

**Comment by jmsche** [comment]
@killerwolf Can you check if the patch proposed in #1572 fixes the issue? Thanks

**Comment by romaricdrigon** [comment]
I also had this issue, with PHP 5.6 Elastica 2.3.2 does not work - 2.3.1 max.
I will have a look at the patch later.

**Comment by romaricdrigon** [comment]
The fix in #1572 solves the issue  🎉

**Comment by p365labs** [comment]
#1572 has been merged closing.
