### ISSUE TITLE
Set max_result_window

### ISSUE THREAD

**Issue by elshobokshy** [ruflin/Elastica#1627]
I have the error : 

```
Result window is too large, from + size must be less than or equal to: [10000] but was [1000000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting. [reason: all shards failed]
```

But when I set `index.max_result_window: 10000` in the yml file it doesn't like me using that format. Any idea why?

Another question, knowing that I can't do `getSize(0)` anymore to get all results, what should I do? As if I don't specify the size I get the default 10. I want all results.

**Comment by mmoreram** [comment]
@elshobokshy what this message is telling to you is that, if you want to access to the element number 10001, your window must be higher than 10001. In this case, you are trying to access the element number 1000000 inside a pagination (from + size), so you should change the window with a larger number.

Said that, this problem is related to Elasticsearch, not to this library. Plese, look for support in [Stackoverflow](https://stackoverflow.com/questions/tagged/elasticsearch) if the question is not about a specific implementation issue of the library.

Thanks :)

**Comment by elshobokshy** [comment]
@mmoreram I want to know where in elastica should I set that index value, how is not this related to Elastica? :-) And about the `getSize(0)`, it was working before I migrate in 2.X, so I'm looking to know how can I have the same functionality in getting all results in the latest version. Thanks!
