### ISSUE TITLE
Pretty printed JSON causes bulk operations to fail.

### ISSUE THREAD

**Issue by janvt** [ruflin/Elastica#1633]
The [Elasticsearch bulk operation docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docs-bulk.html) state: `Because this format uses literal \n's as delimiters, please be sure that the JSON actions and sources are not pretty printed.`

It is possible to create a bulk operation with pretty printed JSON, which then causes the following error: `Malformed action/metadata line [3], expected START_OBJECT but found [VALUE_STRING]`.

Generally, not an issue as `json_encode` does not pretty print by default. But, we ran into this gotcha after a Symfony update to v4, the [default recipe for JMS Serializer](https://github.com/symfony/recipes-contrib/blob/master/jms/serializer-bundle/3.0/config/packages/dev/jms_serializer.yaml) pretty prints in `dev` mode. Could end up catching a lot of people off guard, gave us a good run around to find this...

My suggestion would be to strip `\n` characters in the `__toString` method of the Bulk Action, either only on [line 207](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Bulk/Action.php#L207), or generally on [line 218](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Bulk/Action.php#L218). I can gladly open up a PR.

**Comment by ruflin** [comment]
Interesting issue, thanks for bringing this up. The part I worry here is that we basically add code to Elastic and potentially make it slower for something that is caused by something external. I wonder if there would be a way to have a better error message to tell users what it is and what they need to change.

**Comment by janvt** [comment]
Yeah, we discussed that at length as well. One way to look at it, this would done right after a `json_encode` (and, most likely, a whole bunch of massively expensive JMS OO code), the impact is pretty small in comparison.

Another downside, it is a bit "magical", however, there really is never a case where a `\n` character is valid in a document payload of a bulk operation.

A string search to detect `\n`'s in the `$source` string would be almost as expensive, so throwing an error would be helpful, but would also mean a performance hit. Or, another option is to handle the error from Elasticsearch better and render a hint.

**Comment by ruflin** [comment]
I like the exception part as it would force the developer to fix his application. The question that then is raised: Is this actually a bug or a use case we should support? Should we support it with an additional flag? The problem is that the flag would not work because switching from dev to non dev mode no modifications to the app should be needed. 

For the perfomance impact: Not sure if it would really have an impact. Mainly worried as bulk requests could be pretty large and going through it an replace all `\n` I would assume could have quite an impact.

Haven't really checked the code side yet but do you think there is an easy way that we could provide a better exception on the Elastica side without requiring a change on the ES side?

**Comment by llupa** [comment]
Late to the party but had the same issue. The thing is that `json_encode` can be used with any flag combination / bitmask value, and as far as PHP is concerned this is _valid_ JSON (within PHP). 

I guess if Elastica accepts **only** _valid_ JSON then a validator / validation should take place before building the request to ES, and if that fails, throw an exception that this is an invalid JSON string.

**Comment by ruflin** [comment]
It would be great to have a PR up for a potential change to this discuss this in more detail.
