### ISSUE TITLE
How to check if a document exists?

### ISSUE THREAD

**Issue by ambrous** [ruflin/Elastica#1690]
Hi there,

is there a method to check if document exists?

I found similar methods for indecies and types, but it seems there isn't any one for documents.

If no, are you going to do that?

Thanks in advance!

**Comment by ruflin** [comment]
I think what you are looking for, is the exists query: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html Otherwise if you know the document it, you could use get and catch the exception: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Document.php#L83
