### ISSUE TITLE
Current support status of OpenSearch

### ISSUE THREAD

**Issue by StudioMaX** [ruflin/Elastica#1962]
Maybe you heard about a fork of ElasticSearch 7.10.2 called OpenSearch. It is still the same Amazon ElasticSearch Service, but under a different brand. They claim the API remains backward compatible.
Although it is still in beta, it is already gaining some popularity. But in this Elastica library there is no mention of OpenSearch's brand support status. I think this information would be useful for those who plan to use OpenSearch in the future, given that the version numbers of the original ElasticSearch and the OpenSearch fork will not match.

Links:
https://www.opensearch.org/
https://aws.amazon.com/blogs/opensource/introducing-opensearch/
https://github.com/opensearch-project/OpenSearch

**Comment by ruflin** [comment]
There are no plans for Elastica to support forks of Elasticsearch.

**Comment by StudioMaX** [comment]
Thanks. Is it possible to mention this in readme (or at least briefly that forks like OpenSearch are not supported)? So that no one has any questions, and not to search by repository instead to find out why something is not working with OpenSearch.

**Comment by ruflin** [comment]
Even though it would be pretty easy to add something like that to the README I'm torn on this. I rather focus on what is compatible as it is a finite list instead of what is not compatible. Elastica might work with the forks for some versions but break at some point when the breaking changes to the API are made. I don't know when that happens. One of the reasons not to support forks is to keep it simple to maintain. Same applies for the docs, lets keep it simple and state what we support. It states pretty clearly it supports Elasticsearch.

**Comment by Coffee2CodeNL** [comment]
@ruflin a few years later, but what's the stance nowadays?

**Comment by ruflin** [comment]
@Coffee2CodeNL I don't think anything has changed.
