### ISSUE TITLE
How to get registered query in percolator

### ISSUE THREAD

**Issue by borNfreee** [ruflin/Elastica#444]
Hi,

at the end of  [PercolatorTest.php](https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/PercolatorTest.php)  we get the *name* of registered query `percotest` by matching docs.

My questions: 
* How to get initial query (not only the name)?
* How to get additional parameters registered with the query? In tests this is a "color: blue"

```php
$percolator->matchDoc($doc2);
```

This code just returned name of the registered query without any useful information (query document and additional parameters)

Thank you.

@ruflin

**Comment by im-denisenko** [comment]
I don't know, how it was in 2013, but now ES has good documentation, where pretty clear explained, that percolator is basically just type in index, and that registered queries is documents in this type.

Should we still fix this issue?

**Comment by ruflin** [comment]
I think the issue here is not the missing documentation of elasticsearch, just that some engineers expect that Elastica exposes "all" functions as functions. In general I think we need to have a closer look at the Result object also together with Aggregations. More documentation is also never bad. But I agree that this specific issue can be closed especially as it is quite old.

@borNfreee Please reopen it in case you still see it as relevant.
