### ISSUE TITLE
Weird issue with match_all

### ISSUE THREAD

**Issue by yellow1912** [ruflin/Elastica#641]
I'm using match all and running into very strange issue when the json generated seems to contains extra/malformed info:

https://gist.github.com/yellow1912/8d6b6e6ccc03a37eb717

```
"match_all": "[object] (stdClass: {})"
```

As you can see, somehow the "[object](stdClass: {})" string is added. This is also seen in https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/594

Note: I'm using Elastica + FOSElasticSearch + Symfony 2

**Comment by rayrigam** [comment]
I also have the same issue with my query as displayed by my dev logger. I'm also using Symfony2 with FOS ElasticaBundle. My queries work, but every now and then I have the following error (which is likely due to another issue...?):
>request.CRITICAL: Uncaught PHP Exception Elastica\Exception\ResponseException: "SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed]" at /app/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php line 146 {"exception":"[object] (Elastica\Exception\ResponseException(code: 0): SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed] at /app/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:146)"} []

When the query works the log is something like this:
> elastica.INFO: my_index_name/my_object_name/_search (GET) 335.56 ms {"from":0,"size":15,"sort":{"whatever_stamp":"desc","id":"desc"},"query":{"match_all":"[object] (stdClass: {})"}} []

**Comment by ruflin** [comment]
@rayrigam The error you posted seems to be related to either a connection error or that some of your shards are not available. The important part of the log message is "Failed to execute phase [query_fetch], all shards failed". The question is why all your shards failed. Is it a specific moment that this happens?

**Comment by rayrigam** [comment]
@ruflin So just to make sure, is it ok to have `"match_all": "[object] (stdClass: {})"` in my logs? Have you been able to reproduce that logging error? Should it be an open issue here or in FOSElasticaBundle?
In my case, the "all shards failed" error happens now and then. I don't see any patterns... Perhaps, could it be [due to a corrupt index](http://stackoverflow.com/questions/21157466/all-shards-failed/24908970)?

**Comment by im-denisenko** [comment]
@rayrigam Invalid entry in logs it's not an error at all. It's hack used to force php encode empty array as { } instead of [ ]. If you want to see correct json in logs, you should replace [default](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/LineFormatter.php) monolog formatter to another one.

Also, exception trace you've provide is very short and don't contains most interesting - ES response. Could you try to catch exception and add a `var_dump` of it here?

**Comment by rayrigam** [comment]
@im-denisenko Thanks for explaining why the log shows that text. It was not clear to me.
Regarding my issue, I'll contact my ElasticSearch SaaS provider to see if they can provide the ES response.
