### ISSUE TITLE
Couldn't connect to host, ElasticSearch down? 

### ISSUE THREAD

**Issue by habibun** [ruflin/Elastica#665]
i can't solve this error?

Couldn't connect to host, ElasticSearch down? 

anyone please solve this?

thanks

**Comment by cpmohit** [comment]
Php version 5.4
Elasticsearch version 1.4.2

Issue continously coming........

Fatal error: Uncaught exception 'Elastica\Exception\Connection\HttpException' with message 'Couldn't connect to host, Elasticsearch down?' in /var/www/html/demo/elastic/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:153 Stack trace: #0 /var/www/html/demo/elastic/vendor/ruflin/elastica/lib/Elastica/Request.php(167): Elastica\Transport\Http->exec(Object(Elastica\Request), Array) #1 /var/www/html/demo/elastic/vendor/ruflin/elastica/lib/Elastica/Client.php(587): Elastica\Request->send() #2 /var/www/html/demo/elastic/vendor/ruflin/elastica/lib/Elastica/Index.php(445): Elastica\Client->request('test/', 'DELETE', Array, Array) #3 /var/www/html/demo/elastic/vendor/ruflin/elastica/lib/Elastica/Index.php(157): Elastica\Index->request('', 'DELETE') #4 /var/www/html/demo/elastic/vendor/ruflin/elastica/lib/Elastica/Index.php(223): Elastica\Index->delete() #5 /var/www/html/demo/elastic/index.php(24): Elastica\Index->create(Array, true) #6 {main} thrown in /var/www/html/demo/elastic/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php on line 153

**Comment by ruflin** [comment]
@cpmohit So most of the time it works and sometimes you get this error? I would assume that this should not be related to Elastica itself especially when it works most of the time.

**Comment by crisu83** [comment]
@jacksonj04 Any chance that you could elaborate on what you did wrong because I'm having the same issue with Searchly. Thank you in advance.

**Comment by jacksonj04** [comment]
@crisu83 - if I remember correctly it was down to trailing slashes

**Comment by crisu83** [comment]
@jacksonj04 thanks, adding a trailing slash to the URL fixed it.

**Comment by qiaofei32** [comment]
stop iptables
disable Selinux
then try again

**Comment by tolousn** [comment]
Out of nowhere I started getting these. The crazy part is that it's on and off. It works for few minutes then stops working, both on local and live server at the same time. Is there an issue with elastica server? Is anyone else having that issue today?

**Comment by Zyqsempai** [comment]
@tolousn Hi there, can you describe your server part?Do you youse ElasticSearch as a SAAS or your own on your local machine? Maybe docker container?

**Comment by jdacjohn** [comment]
I inherited a site that I'm transferring from one domain to a new domain.  Total nightmare because I can't even access the server that the old site is hosted on.  Was basically given a tar.gz and told to "get to it."  The site is up and running but I get this error (Couldn't connect to host, Elasticsearch down?) when I try to search.

I have uninstalled and reinstalled from the dashboard, but I don't even know where to begin looking for where the host and port is set for this add-on.  What am I missing?  Is there something that has to be installed on the new server to allow Elasticsearch to run on Concrete5?  Concrete5 version is 8.3.1 and Elasticsearch version is 0.0.0 from what I can see.

Please help.  Uninstalling Elasticsearch from the site at the dashboard does not restore search C5 search functionality.

**Comment by ruflin** [comment]
@jdacjohn TBH a bit confused by your details above. I don't remember a version 0.0.9 of Elasticsearch and how does Concrete5 come into play here? What version of Elastica are you using? Can you connect to Elasticsearch via curl?

**Comment by jdacjohn** [comment]
@ruflin  Thanks for replying.  I may be barking up the wrong tree as I'm not even sure what Elasticsearch is, as I'm quite confused as well.  The site is a Concrete5 site.  In the dashboard (when logged in as admin) when I go to 'Extend Concrete5' it shows "Elastic Search v.0.0.0 - Replaces default search index with elasticsearch' is installed.   This functionality resides in a folder named 'elastic' in the packages folder of the C5 install folder.  I believe it is a wrapper project that contains this project

I've been tasked with moving this site from one domain to another; i.e., dialogo-americas.com -> dialogo-america.com.

The search works fine on the dialogo-americas.com site, but does not work on the dialogo-america.com site.  On the new domain, I get the error message indicated by this thred.  I cannot find any information about this Concrete5 add-on basically anywhere so I ended up here.

When you ask if I can connect to Elasticsearch via curl, I don't even know where I would connect TO.  I am sure Elasticsearch is jut fine and this is probably a simple config issue but I cannot find anything on this anywhere I have looked for the last week and IMHO, the documentation for Concrete5 is written only for the blue sky perspective.  The only thing I ever find there are unanswered questions from at least 2 years ago, and I've been unable to find anything related to this add-on in the Concrete5 community to this point.

I may have a fundamental misconception about how Elasticsearch works.  If you're picking up on any frustration on my part, I apologize.  This migration has been a nightmare for 2 weeks running beginning with the fact that due to misconfigurations, ftp, shell, and WHM/cPanel access to the original server is impossible, and the hoster doesn't seem to want to do anything about it.

**Comment by jdacjohn** [comment]
If this is any help at all, here is the log output from the most recent search attempt:

[2018-02-25 23:43:46] elastica.ERROR: Elastica Request Failure {"exception":"[object] (Elastica\\Exception\\Connection\\HttpException(code: 0): Couldn't connect to host, Elasticsearch down? at /home/dialogoamerica/public_html/packages/elastic/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:180)","request":{"path":"ccm_dialogo/ccm_page/_search","method":"GET","data":{"query":{"bool":{"must":[{"prefix":{"cPath":{"value":"/en/","boost":1}}},{"simple_query_string":{"query":"carrots","fields":["cName^1.5","cDescription^1.2","_all"],"locale":"en_US"}}],"should":[{"range":{"cDatePublic":{"boost":6,"gte":1516923826000}}},{"range":{"cDatePublic":{"boost":4,"gte":1514245426000}}},{"range":{"cDatePublic":{"boost":3,"gte":1511653426000}}},{"range":{"cDatePublic":{"boost":2,"gte":1488066226000}}},{"range":{"cDatePublic":{"boost":1,"gte":1456443826000}}}]}},"sort":[{"cDatePublic":{"order":"desc"}},"_score","_doc"]},"query":{"from":0,"size":10},"connection":{"config":{"url":null,"bigintConversion":false},"host":"localhost","port":null,"path":null,"proxy":null,"transport":null,"persistent":true,"timeout":null,"connections":[],"roundRobin":false,"log":false,"retryOnConflict":0,"username":null,"password":null,"enabled":false}},"retry":false} []

**Comment by ruflin** [comment]
As I don't know anything about Concrete5 lets try to get this out of the equation.

There is Elastica as a client and Elasticsearch where the data is stored / processed etc. The above you posted is an error that happens if the client can't connect to the server. So it seems from the client view the Elasticsearch host is not reachable.

Few questions which you should answer on your side:

* Where is Elasticsearch running?
* Where is Elastica running?
* Are these the same machines or different ones?
* What are the settings you have configured on the Elastica side to connect to ES
* What are the settings on the Elasticsearch
* Which versions are you using for Elastica and which version of Elasticsearch?

**Comment by jdacjohn** [comment]
Thanks Nicolas, this helps.  The client appears to be 3.2.2 (from the CHANGELOG.md), and ElasticSearch v 5.3.

Here's a high-level of the composer project (I'm not including everything in here, like composer, guzzlehttp, etc.)

Elastic ->  Top level project folder (This is the project that was created to install ElasticSearch as a package in concrete5 and that's the last I'll say about Concrete5).

    vendor ->  
        elasticsearch  -- I'm guessing this is the elasticserach provider?)
        ruflin
            elastica  -- I'm guessing this is the client your're referring to.
   
The config for the client shows:  (in elastic->config -> elastic.php):
return [
    'hosts' => [
        'localhost'
    ],
    'index' => 'ccm_dialogo',
    'type' => 'ccm_page'
];

From this, I'm *guessing* that the client and the search should be running on the same machine?  I have looked all through the project tree and these are the only settings I can find.  

Thanks for your help.

**Comment by jdacjohn** [comment]
Update.  ElasticSearch is not running on the new machine - It's not even installed.  Everything I've been looking at is for the client.  So, ES not running means, yes it's down on localhost.  I installed ElasticSearch 5.3 (to match) site code on my local dev server, configured and fired it up.  I'm able to hit the ElasticSearch host, so now I've now graduated to this error when I try to perform a search on the site in dev:

no such index [index: ccm_dialogo]

Which makes perfect sense now.  This tells me that the index that was built for the old live site is residing on that server in wherever path:data is set to on the old server, and of course, since that server is inaccessible via WHM, cPanel, SSH, or even FTP (it basically locks up my network and I think takes down the ISP area subnet as well - too much coincidence in trying to connect to that server and having outages occur right at that moment that affects both me and my neighbors...), I'm basically screwed and am trying to rebuild the index using the IndexElastic.php that came with the site code.  

But of course, it's not indexing because it was built for an older version of the Concrete5 core and the site had been updated prior to me getting it.  No biggie, it's only like 26000 pages.  So, thanks for your help - just you pointing out the simple distinction between the ElasticSearch and the ElasticSearch client put me on the right track.

**Comment by ruflin** [comment]
@jdacjohn Glad I was helpful.

**Comment by chamarts** [comment]
huh, I have same issue where in it works in my laptop (windows) connecting to ES remote in AWS. But when the client sits on aws box it doesn't work. Its same issue with elasticsearch-php client as well. I wonder whats the issue with php. kibana on same machine connects fine to same ES instance. 

this is driving me crazy

**Comment by chamarts** [comment]
huh... I need to set this in linux 

sudo setsebool -P httpd_can_network_connect true
