### ISSUE TITLE
Memory limit

### ISSUE THREAD

**Issue by happydude** [ruflin/Elastica#754]
We run zend server and have left the memory limit in php.ini at their default of 128MB.

Occasionally I'm running into the memory limit when using addDocument,  The files are around 25MB.  Checking my memory usage just before addDocument shows around ~40MB.

The trace shows it hitting the memory limit in Http.php with $content = str_replace('\/', '/', $content);

Elastica\Transport\Http::exec() at /www/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php: 108
Elastica\Transport\Http::send() at /www/vendor/ruflin/elastica/lib/Elastica/Request.php: 168
Elastica\Request::request() at /www/vendor/ruflin/elastica/lib/Elastica/Client.php: 590
Elastica\Client::request() at /www/vendor/ruflin/elastica/lib/Elastica/Index.php: 444
Elastica\Index::request() at /www/vendor/ruflin/elastica/lib/Elastica/Type.php: 511
Elastica\Type::addDocument() at /www/vendor/ruflin/elastica/lib/Elastica/Type.php: 90
Elastica\Type::searchUpdate() .........

Increasing the memory limit works, so my question is there a recommended memory limit when using elastica?  I was concerned about just increasing the limit and band-aiding over a deeper problem.

Thanks

**Comment by ruflin** [comment]
If you want to add files with 25MB, I suggest you add more then 128MB. The reason is that the full file is read and then also hold in the cache so I assume at least double the memory size of the file is needed. The memory needed for Elastica heavily depends on the file size and how many documents you add at once. I suggest in your case at least 192MB files. If the process is long running, probably 256MB would make sense. Of course it always also depends on what other things are running the the same request.

Does this help?

**Comment by happydude** [comment]
Yes that does, thank you for the advice.
