### ISSUE TITLE
setHightlight not following the Elasticsearch documentation ?

### ISSUE THREAD

**Issue by jcrombez** [ruflin/Elastica#815]
I'm trying to follow this documentation : 

http://www.elastic.co/guide/en/elasticsearch/reference/1.3/search-request-highlighting.html

Who says :

```json
{
    "query" : {...},
    "highlight" : {
        "fields" : {
            "content" : {}
        }
    }
}
```
So i tried :

```php
$query->setHighlight([
    'fields' => [
        'content',
    ]
]);
```
But the resulting Json is invalid for elasticsearch parser :

```json
"highlight": {
    "fields": [
        "content"
    ]
}
```
So i tried this :

```php
$query->setHighlight([
    'fields' => [
        'content' => []
    ]
]);
```
Wich give me this : 

```json
"highlight": {
    "fields": [
        "content": []
    ]
}
```

Which is valid for the parser but not what the hightlight expect, so the feature is just ignored.

Is it possible to achieve the same hightlight syntax as stated in the documentation ?

**Comment by ruflin** [comment]
Have a look into the tests below: 

* https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/Query/HighlightTest.php#L28
* https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/Aggregation/TopHitsTest.php#L296

Elasticsearch expects an "object" and not an array. So if you need {} after content, use an empty stdClass() object. As soon as "content" is an object, it should also make an object out of fields instead of an array.

**Comment by jcrombez** [comment]
Thanks a lot for tour help.
