### ISSUE TITLE
Migrate to Elasticsearch 2.0

### ISSUE THREAD

**Issue by ruflin** [ruflin/Elastica#946]
Elasticsearch 2.0 bring several BC breaks. Adaptions must be made. Here is a checklist of open issues:

* [x] Status API was removed:
  * https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-status.html
  * https://www.elastic.co/guide/en/elasticsearch/reference/2.0/indices-status.html
* [x] Thrift support was removed
* [x] Facets were replaced by aggregations and removed -> Facets are removed from the code.
* [x] Memcached support was removed
* [x] Bulk UDP API has been removed
* [x] Delete by query was moved to a plugin?
* [x] Error handling got more extensive. Example:

Before:
```
{
  "error" : "IndexMissingException[[lkwer] missing]",
  "status" : 404
}
```
After
```
{
  "error" : {
    "root_cause" : [ {
      "type" : "index_not_found_exception",
      "reason" : "no such index",
      "resource.type" : "index_or_alias",
      "resource.id" : "334",
      "index" : "334"
    } ],
    "type" : "index_not_found_exception",
    "reason" : "no such index",
    "resource.type" : "index_or_alias",
    "resource.id" : "334",
    "index" : "334"
  },
  "status" : 404
}
```

**Comment by yellow1912** [comment]
thank you. I'm closely following your progress here as well.

**Comment by Lumbendil** [comment]
Going to follow this issue aswell :) Btw, you have _Thrift support was removed_ dupplicated.

**Comment by ruflin** [comment]
@Lumbendil Thanks. That is what you get using the Union merge :-)

**Comment by Lumbendil** [comment]
Yay, this got updated.

Is there any simple issue which could be tackled by someone who hasn't delved to much on the library, to contribute a bit?

**Comment by ruflin** [comment]
@Lumbendil Good question. Probably the easiest to start is get a clone from the elasticsearch-2.0 branch locally, install docker and docker-compose and run `make tests`. This will output quite a few failing tests. Pick one that you think is easy to fix. 

Take for example the Fuzzy queries which are failing: https://travis-ci.org/ruflin/Elastica/jobs/87636268 Haven't looked into it by I assume the syntax changed somehow.

**Comment by Lumbendil** [comment]
I already have docker-compose (Thanks for providing a test env with the lib!) I'll try to tackle some of them if I can get time for it :D

**Comment by ruflin** [comment]
Small update here: I now went through all the "broken" tests. The small ones I fixed directly, all the others I marked as skipped and tryed to add some details. Now it should be easier for everyone to pick a test and try to figure out what is broken: https://travis-ci.org/ruflin/Elastica/jobs/89254674

It would be nice if someone could tackle the delete by query issues. I will look into Status and potential remove it completely.

**Comment by ewgRa** [comment]
I look to deleteByQuery. It will be removed in ES 2.0, they suggest use ScrollAndScan and than perform bulk delete by document ids.

Use this advice as is in Elastica will cause CPU performance problems, because instead of one query, we will have read documents (create objects) and then send delete requests.

They implement it as plugin https://github.com/elastic/elasticsearch/blob/master/docs/plugins/delete-by-query.asciidoc#delete-by-query-plugin-reason

I think deleteByQuery not require any changes, seems it is compatible with this new plugin. There is just must be added good exception message if plugin is not installed and also in tests there is checks needed, and if plugin not installed - just mark it skipped.

@ruflin what do you think?

**Comment by ruflin** [comment]
@ewgRa Agree. We should install the plugin as part of the setup and have a good exception in case it is no installed. Should also be part of the code docs.

I'm actually not sure if something like attachment is used and an the plugin is not installed. Do we get a reasonable exception?

@ewgRa Are you going to proceed here?

**Comment by ewgRa** [comment]
@ruflin I install docker image, but seems there is no any plugin installed, many tests is skipped, because no plugin. But I need to check.

Yes, yesterday I start looking to deleteByQuery issue. Tomorrow will continue on it, maybe today if I will have time. If it is not urgency, let me dig it more.

About exceptions this is also question, because I don't check how ES answer when this plugin is not installed. Also will check it.

**Comment by ruflin** [comment]
@ewgRa Let me have a brief look if I can get the plugin to install. Perhaps faster as I did it before.

**Comment by ewgRa** [comment]
Seems deleteByQuery have a bug: https://github.com/elastic/elasticsearch/issues/14758

Will wait confirmation or explanations.

**Comment by ruflin** [comment]
Ok, thanks.

**Comment by ewgRa** [comment]
PR #977 that adds check plugin exists for deleteByQuery. As I see from Image for example, there is no messages like "Image plugin not installed" when developer try query something related to Image plugin. That means that (Test|Index)::deleteByQuery also not required changes.
Fail test I think will be fixed when bug in elasticsearch will be confirmed or explained.

**Comment by Floyd25** [comment]
elastic/elasticsearch#14758 was closed 4 days ago. They said it wasn't a bug

**Comment by ewgRa** [comment]
@Floyd25 thanks for watching progress. Actually it is already done https://github.com/ruflin/Elastica/pull/979 , actually it was problem in test.

**Comment by Lumbendil** [comment]
@ruflin out of curiosity, other than verifying there haven't been introduced new bugs, is there anything else which should happen to go from beta to 3.0?

**Comment by ruflin** [comment]
@Lumbendil Not from my point of view. But I want that at least some people test it to see if everything works as expected. I would probably give it 1-2 weeks. Your thoughts?

**Comment by Lumbendil** [comment]
Just asking because I have a dependency to it inside a repo which is the one I depend on my projects, so I have to write twice the code, and I wanted to get an estimate on how long I'll have to depend on "3.0.0@dev" :)

In the case of a library such as this I'd be more inclined to go 3.0.0 and release bug fixes as they come, since people shouldn't depend on "*" and if they do and see `composer update` updating to a new major they should worry a bit about what might have changed.

**Comment by Floyd25** [comment]
Sorry, to ask on this issue page, but: 3.00 would be compatible with elastic search 2.0? We're about to start a new project and would love to use es 2.0 from the start. any hints you could give me if 3.x would be stable enough?

**Comment by ruflin** [comment]
@Floyd25 Yes, Elastica 3.0.0 is compatible with elasticsearch 2.0. I highly recommend to directly start with 2.0. For your question on stability: It was released yesterday. Also check the comment above from @Lumbendil :-)

**Comment by Lumbendil** [comment]
@Floyd25 it's Elastica 3.0 (and I believe 3.x) is written for ElasticSearch 2.x, so it is compatible. As far as stability of 3.0 goes, it was tagged just yesterday, but since ES 1.0 to 2.0 had more deprecations than BC breaks, it should be pretty stable.

Can't assure there won't be bugs.

PS: Ninja'd

**Comment by ruflin** [comment]
@Lumbendil There are too many "shouldn't" and "might" in the sentence. I basically agree with you but I'm always surprise how many actually directly use master for their apps :-)

**Comment by Lumbendil** [comment]
@ruflin if they use master, they are already using 3.0, so what's the danger on that case? Also, pretty common when people abuse "*" is the "minimum-stability" "dev", so those are using 3.0 already aswell.

**Comment by ruflin** [comment]
@Lumbendil Lets give it at least a few days for my own sanity :-) Happy to then jump to 3.0.0 directly. The good news, no new issues popped up since yesterday.

**Comment by Lumbendil** [comment]
:+1: will stick to `~3.0.0@dev` for the time being. As a side note, I read you have no problem on BC breaks on minors (3.0 to 3.1), don't you usually keep compatibility with the previous method signature / keep the previous method pointing to the new method though?

Asking so I can just do `~3.0` and "forget about it" instead of `~3.0.0` :)

**Comment by ruflin** [comment]
@Lumbendil I do that whenever possible, in case just the method change. Make sure you don't use any deprecated methods as these I'm willing to remove in Minor versions. It was a bad habit to keep them around for too long in recent release and was a bit of an issue recently. 

In case there are some heavy BC breaks, I make sure I let people now. @ewgRa is our champion here in making things easy for people to migrate to the next version.

You should be fine with `~3.0`. I just hope you never going to refer to my post here in case your app breaks ;-)

**Comment by Lumbendil** [comment]
@ruflin as long as methods are deprecated beforehand, I'll go with `~3.0` :smile:

**Comment by ruflin** [comment]
Closing this issue as Elastica 3.0.0-beta1 was released
