### ISSUE TITLE
Elasticsearch 2.0

### ISSUE THREAD

**Issue by jdc18** [ruflin/Elastica#993]
Are there any issues with Elastica and Elasticsearch 2.0, I did some tests and it seems to work fine with ES 2.0.  On the docs it says that it supports up to ES 1.7 and I know there are some major changes on from 1.7 to 2.0.
I can see that there is a branch for 2.0, is that branch stable enought?

Thanks

**Comment by Lumbendil** [comment]
There is work being done, some queries might work due to them keeping the same syntax from 1 to the other.

You can check the state on #968

**Comment by ruflin** [comment]
@jdc18 18 out of about 900 tests still fail. Here are all listed: https://travis-ci.org/ruflin/Elastica/jobs/92800144#L1668. Most of the queries should work as expected by now. I would not recommend the branch for production as it is a development branch but running it with elasticsearch 2.0 and reporting problems (or success) is also of big help. Otherwise the fastest way to get it releaed and out is picking up one of the failing tests and opening a PR to fix it.

**Comment by ruflin** [comment]
@jdc18 After a fixing spree yesterday night, only two are left. As soon as we get these fixed, I plan to do a beta1 release.

**Comment by jdc18** [comment]
@ruflin great work, I did a pull yesterday and I was checking your code nice work

**Comment by ruflin** [comment]
Closing this issue as Elastica 3.0.0-beta1 is now out: http://elastica.io/2015/11/26/release-3-dot-0-0-beta1/
